name: CI

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 3

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node: [12, 14, 16]

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3.0.2

      - name: Install Node
        uses: actions/setup-node@v3.1.1
        with:
          node-version: ${{ matrix.node }}

      - run: npm ci

      - run: npm run lint

      - run: npm test

      - run: npm run build

      - run: npm run package
